import type { Metadata } from "next";

import "@style/mediaPlayerGlobal.css";

import { MediaPlayerProvider } from "@/context/PlayerContext";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <MediaPlayerProvider>
            {children}
        </MediaPlayerProvider>
    );
}
