import type { Metadata } from "next";

import { Analytics } from "@vercel/analytics/next"

import "@style/globals.css";
import "@style/mediaPlayerGlobal.css";

import 'dseg/css/dseg.css';

import {
  Geist,
  Geist_Mono,
  Barlow_Semi_Condensed,
  Eagle_Lake
} from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "block"

});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "block"
});

const barlowSemiCondensed = Barlow_Semi_Condensed({
  variable: "--barlow-semi-condensed",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "block"
});

const eagleLake = Eagle_Lake({
  variable: "--eagle-lake",
  weight: "400",
  display: "block"
});


export const metadata: Metadata = {
  title: "Tetzaveh Media Player",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${barlowSemiCondensed.variable} ${eagleLake.variable}`}
    >
      <body>
        {children}
        <Analytics />
      </body>
    </html >
  );
}
